### ISSUE TITLE
Brainstorming

### ISSUE THREAD

**Issue by jwl317** [jwl317/2019Fall-OSS-Team9#3]
Upload your ideas

**Comment by loffy1411** [comment]
Web chatting - difficult

**Comment by jwl317** [comment]
[PHAMTOMBOT](https://18-1-skku-oss.github.io/2018-1-OSS-E1/)
[18-1-SKKU-OSS/2018-1-OSS-E1](https://github.com/18-1-SKKU-OSS/2018-1-OSS-E1#notification-settings)

**Comment by jwl317** [comment]
[DJANGO PROJECT](https://17-1-skku-oss.github.io/116A/index.html)

**Comment by chocoPenguin** [comment]
정보보호개론에서 수업듣던중 유사난수 생성기에대해서 조사해봤는데, MS에서 제공하는 난수생성기는 SEED를 설정할 수가 없어서 교육용으로 SEED를 넣으면 어떻게 난수가 생성되는지 보여주는 프로그램

난이도: 하~중

https://en.m.wikipedia.org/wiki/Pseudorandom_number_generator

**Comment by chocoPenguin** [comment]
Unity 프로젝트나 안드로이드 스튜디오!
안드로이드 스튜디오로 카카오톡 비슷한 프로그램을 만든 적이 있는데, 경험을 살리는것도 좋을 것 같아요

**Comment by jwl317** [comment]
> Unity 프로젝트나 안드로이드 스튜디오!
> 안드로이드 스튜디오로 카카오톡 비슷한 프로그램을 만든 적이 있는데, 경험을 살리는것도 좋을 것 같아요

- 한 번 더 안해본 경우 어렵지 않을까용?
+ 보여줄게 많다

**Comment by jwl317** [comment]
> [PHAMTOMBOT](https://18-1-skku-oss.github.io/2018-1-OSS-E1/)
> [18-1-SKKU-OSS/2018-1-OSS-E1](https://github.com/18-1-SKKU-OSS/2018-1-OSS-E1#notification-settings)

너무 번역만 한듯?

**Comment by jwl317** [comment]
Android Emulator
- 단순 doc 수정은 난이도가 너무 낮아질듯

**Comment by loffy1411** [comment]
수강신청 줍기 앱 발전

**Comment by mk5436** [comment]
KNN classifier 등등 머신러닝 API

**Comment by jwl317** [comment]
Keras [https://github.com/KerasKorea/KEKOxTutorial](url)

**Comment by loffy1411** [comment]
카테고리를 나눠봅시다
1. 번역
2. 웹
3. 앱
4. 머신러닝
5. 개발
6. 단순화
7. VR

**Comment by chocoPenguin** [comment]
> Unity 프로젝트나 안드로이드 스튜디오!
> 안드로이드 스튜디오로 카카오톡 비슷한 프로그램을 만든 적이 있는데, 경험을 살리는것도 좋을 것 같아요

만약 안드로이드 스튜디오 만들면 https://tumblbug.com/bigpicture 이런 일정관리 눈에 잘 띄게 해주는거, 혹은 linux에서 되는 프로그램도 괜찮을것같아요

**Comment by mk5436** [comment]
오토 멀티쓰레딩 프로그램
(자동 openMP)

**Comment by mk5436** [comment]
12월 5일 예비발표(평가x)
12월 19일 본발표(평가o)

**Comment by chocoPenguin** [comment]
VR 한다면 방탈출게임!

**Comment by chocoPenguin** [comment]
> 카테고리를 나눠봅시다
> 
> 1. 번역
> 2. 웹
> 3. 앱
> 4. 머신러닝
> 5. 개발
> 6. 단순화
> 7. VR

번역은 간편하고 쉬울 것 같긴 한데, 좋은 평가를 받을 수 있을지는 모르겠어요

**Comment by loffy1411** [comment]
> 카테고리를 나눠봅시다
> 
> 1. 번역
> 2. 웹
> 3. 앱
> 4. 머신러닝
> 5. 개발
> 6. 단순화
> 7. VR

단순화는 이미 많이 진행된 부분이 많아서 더 할것이 있을지가 의문

**Comment by jwl317** [comment]
예전 호치민과기대 학생들과 콜라보  보안?
--ve 단 doc 없음 ㅜㅜ
[Cooking helper](https://github.com/yunjiyunji/cooking_helper)

**Comment by mk5436** [comment]
에브리타임 앱 검색어 등등 단어 필터링하는 어플 또는 웹사이트(크롤링 후 뷰어)

**Comment by loffy1411** [comment]
> 에브리타임 앱 검색어 등등 단어 필터링하는 어플 또는 웹사이트(크롤링 후 뷰어)

에타 웹에 직접적으로 필터링을 적용하는 것보다는 게시판 글들을 크롤링 해와서 필터링을 거친다음 따로 보여주는 게 더 쉬울 것 같습니다!

**Comment by mk5436** [comment]
> 에브리타임 앱 검색어 등등 단어 필터링하는 어플 또는 웹사이트(크롤링 후 뷰어)

[everytime_opensource_license.txt](https://github.com/jwl317/2019Fall-OSS-Team9/files/3793489/everytime_opensource_license.txt)

**Comment by chocoPenguin** [comment]
1. 깃허브 커멘트 작성시 본문+커멘트 가 아래에 달리는데, 본문 아래에 커멘트가 달리게, 혹은 커멘트를 클릭 했을때 원래 본문 위치로 가게(카톡 답장 기능과 유사하게)

**Comment by mk5436** [comment]
> 1. 깃허브 커멘트 작성시 본문+커멘트 가 아래에 달리는데, 본문 아래에 커멘트가 달리게, 혹은 커멘트를 클릭 했을때 원래 본문 위치로 가게(카톡 답장 기능과 유사하게
> 2. 카톡 대화하는 것 처럼 본인이 올린 이슈의 경우 프로필이  왼쪽, 다른 사람이 올린 것의 경우 프로필이 오른쪽에 위치하게
> 3. 위 1,2의 모드를 구현해서 선택해서 적용가능하게...!

[https://github.com/marketplace/devhub-app](url)

**Comment by jwl317** [comment]
Kakao Talk Channel API + Github
[Android](https://developers.kakao.com/docs/android/kakao-talk-channel)

**Comment by chocoPenguin** [comment]
1. 유사난수 생성기 API
2. VR 방탈출
3. 안드로이드 에뮬레이터 보완
4. 수강신청 내 기능 보완(경쟁률 계산기 + 자리 남는 과목 알림)
5. 리눅스/안드로이드 일정관리
6. 케라스 보완
7. 리눅스 스케쥴러
8. 에브리타임 필터링 어플/웹사이트
9. 깃허브 기능 추가
10. 깃허브 + 카카오톡 채널 API
