### ISSUE TITLE
주제 실현 가능성 조사

### ISSUE THREAD

**Issue by chocoPenguin** [jwl317/2019Fall-OSS-Team9#4]
1. 유사난수 생성기 API
2. VR 방탈출
3. 안드로이드 에뮬레이터 보완
4. 수강신청 내 기능 보완(경쟁률 계산기 + 자리 남는 과목 알림)
5. 리눅스/안드로이드 일정관리
6. 케라스 보완
7. 에브리타임 필터링 어플/웹사이트
8. 깃허브 기능 추가
9. 깃허브 + 카카오톡 채널 API

**Comment by chocoPenguin** [comment]
1. 유사난수 생성기 API
7. 에브리타임 필터링 어플/웹사이트
9. 깃허브 + 카카오톡 채널 API

**Comment by loffy1411** [comment]
4, 7, 9

**Comment by jwl317** [comment]
깃허브 + 카카오톡 채널 API
리눅스/안드로이드 일정관리

**Comment by mk5436** [comment]
7,8,9 
에브리타임 필터링 어플/웹사이트, 깃허브 기능 추가, 깃허브+카카오톡 채널API

**Comment by jwl317** [comment]
> 깃허브 + 카카오톡 채널 API
> 리눅스/안드로이드 일정관리

5, 9

**Comment by chocoPenguin** [comment]
> 1. 유사난수 생성기 API
> 2. VR 방탈출
> 3. 안드로이드 에뮬레이터 보완
> 4. 수강신청 내 기능 보완(경쟁률 계산기 + 자리 남는 과목 알림)
> 5. 리눅스/안드로이드 일정관리
> 6. 케라스 보완
> 7. 에브리타임 필터링 어플/웹사이트
> 8. 깃허브 기능 추가
> 9. 깃허브 + 카카오톡 채널 API

7. 에브리타임 필터링 어플/웹사이트 :  이지선, 문성암
9. 깃허브+카카오톡 채널 API  :  하예송, 이재원
다음주 목요일까지 각자 조사해오기!!

**Comment by jwl317** [comment]
회의 합시다 ㅎㅎ

**Comment by chocoPenguin** [comment]
8번 조사 결과
1.	Github에서 Pull request가 새로 올라왔는지 알아내기
https://git-scm.com/book/ko/v2/GitHub-GitHub-%EC%8A%A4%ED%81%AC%EB%A6%BD%ED%8C%85#_web_hook
웹훅 깃헙 공식 레퍼런스: https://developer.github.com/webhooks/
 
(예시)슬랙에 깃허브 메시지 전달: https://www.44bits.io/ko/post/notifying-github-event-by-using-github-webhook

2.	발생한 이벤트를 카카오톡에 메시지 보내기
https://developers.kakao.com/docs/js/kakaotalklink

[깃헙풀리퀘스트-카카오톡API조사.docx](https://github.com/jwl317/2019Fall-OSS-Team9/files/3819079/-.API.docx)

**Comment by loffy1411** [comment]
7번 조사 결과
1. 난이도 : 중 ~ 중상
2. 구현 방식
 - 전에 말했던 대로 웹 크롤링을 이용한 새로운 페이지 구현
 - 플러그인 방식
 - 크롬 확장 기능 이용 (NEW!) : 대부분 크롬 많이 쓰니까 확장 기능 이용하면 굳이 플러그인 만들지 않아도 됨
3. 사용언어 : 일단 자바 스크립트

**Comment by mk5436** [comment]
7번조사 결과
난이도 :  중하~ 중
우선 사용약관에 제9조 2항 데이터베이스의 일부 또는 전체는 복제 배포 방송 전송을 회사 승인 없이 할수 없다는데 과제하면서 이부분을 침해하는게 아닌지 알아야합니다.

가능하다면 웹크롤링 후 파이썬으로 핸들링하는게 가장 쉬운 것 같습니다.

특정문자를 필터링하는 것에 대해서 
숭실대학교 커뮤니티가 인공지능을 이용해서 필터링(아직 정확도는 높진 않은것 같습니다.)
인공지능을 이용한다면 난이도를 올릴 수 있습니다.

참고자료 :  
에브리타임 크롤링 관련
에브리타임 게시글 및 댓글로 wordcloud만들기
파이썬, 셀레니움, 
최남기 https://namki-learning.tistory.com/17
이정민 https://jeongmin-lee.tistory.com/53

에브리타임 자동 크롤링/ 봇 시스템
https://blog.naver.com/kbs4674/221460241196
댓글들을 조사해서 자동 답글 달아주는 봇 만들기
1. 사용 언어 / 웹프레임워크 : Ruby 2.4 / Ruby on Rails 5.1.6
2. Github : https://github.com/kbs4674/everytime_crawlbot

**Comment by jwl317** [comment]
8번 깃허브+카카오톡 채널 API 조사 내용

Slack+Github [github source](https://github.com/marketplace/slack-github)
예제로 보면서 document를 읽어봤습니다
[document](https://github.com/integrations/slack/blob/master/README.md)

저희가 카톡에 응용해/구현해볼 수 있는 추가 할 수 있는 기능들 생각해보았는데
\github 커멘드 사용
1. pull request message 알려주기
2. 카톡에서 issue 시작하기
3. 카톡으로 code line 직접 보여주기


카카오톡 채널 연동 [Kakao tech source](https://developers.kakao.com/docs/sync/kakao-talk-channel)
난이도: 상
1) 앱 생성 단계에서 키 값 제대로 받아오는 작업부터 시작
[resource](https://developers.kakao.com/docs/android/getting-started#%EC%95%B1-%EC%83%9D%EC%84%B1)

**Comment by jwl317** [comment]
1. 카카오톡은 될지 않될지 모르겠다
2. 단순 위젯을 만들거면 기능을 더 추가해야될 것 같다

**Comment by loffy1411** [comment]
일단 깃헙 알림 기능이 아직 정해지지 않은 부분이 많아서 어떤 기능을 할지 구체적으로 정해보고 안된다 싶을 때 다른 주제로 하는게 좋을 것 같네요

**Comment by chocoPenguin** [comment]
![image](https://user-images.githubusercontent.com/39482958/68387235-36dc6f80-01a1-11ea-939a-cc41ec62a4ec.png)

**Comment by jwl317** [comment]
![image](https://user-images.githubusercontent.com/32070792/68387400-90449e80-01a1-11ea-969a-6d7dbe66e0be.png)

**Comment by jwl317** [comment]
1. 알림기능
2. 채팅에 issue하면 Github issue에 올라가에끔 하자

**Comment by jwl317** [comment]
> 1. 알림기능
> 2. 채팅에 issue하면 Github issue에 올라가에끔 하자

1번 우선시
2번은 나중에 시간 나면..

1번의 product outcome을 통일합시당

**Comment by jwl317** [comment]
기본적으로 URL이 제공되는가?
제공이 된다면,
웹훅내에서 제공하는 함수를 가지고 {미지수}
알림 기능이 작동이 되는지를 확인 한다

그런 다음에 


최후의 수단
깃허브 로그인 되어있고
깃허브 창이 닫혀있어도
새로운 활동에 대해 크롬 브라우저 알림 뜨게 하기

**Comment by jwl317** [comment]
[Webhooks](https://developer.github.com/webhooks/)

**Comment by jwl317** [comment]
webhook 자동적으로 개인 forked repository 에 활성화될 수 있게 하는 작업도 어려울 것 같다

**Comment by chocoPenguin** [comment]
Webhook을 이용한 방법을 사용하려면 Fork -> Webhook을 일일이 등록해야 함!!
팀을 2개로 나누어서
1팀: 깃허브 -> 프로그램 으로 알림을 전송하는 방법
2팀: 프로그램에서 화면에 알림 띄우기
로 구현하면 좋을것같아요

**Comment by jwl317** [comment]
일요일 저녁 10시 회의 resume!
1. 어떻게 하면 될 것 같다~
2. 안될 것 같으면 뭘 해야겠다~
생각해서 정리 & 공유

**Comment by chocoPenguin** [comment]
![image](https://user-images.githubusercontent.com/39482958/68389713-f253d280-01a6-11ea-9185-c9c364f322be.png)
